#!/bin/bash

srcdir="src"
destdir="dist"
staticdir="static"
template="src/template.html"

rm -rf ${destdir}/
mkdir ${destdir}/

function generate() {
	in=${1}
	path=${in#$srcdir}
	out="${destdir}${path%.*}.html"
	dir=$(dirname ${out})
	mkdir -p ${dir}
	pandoc --template=${template} ${in} > ${out}
	echo "${out}"
}

for i in $(find ${srcdir}/ -type f)
do
	if [[ ${i} != ${template} ]]; then
		generate ${i}
	fi
done

cp -a ${staticdir}/. ${destdir}/
echo "${destdir}/${staticdir}/"