#!/bin/bash

VERSION="0.1"
SRCDIR="${PWD}/src"
DESTDIR="${PWD}/dist"
STATICDIR="${PWD}/static"
TEMPLATE="${PWD}/template.html"

conf="${PWD}/.ssg"
if test -f "${conf}"; then
	. ${conf}
fi

build() {
	rm -rf ${DESTDIR}/
	mkdir ${DESTDIR}/
	for i in $(find ${SRCDIR}/ -type f,l); do
		generateHTML ${i}
	done
	cp -a ${STATICDIR}/. ${DESTDIR}/
	echo "build complete"
}

generateHTML() {
	in=${1}
	path=${in#$SRCDIR}
	base=${path%.*}
	out="${DESTDIR}${base}.html"
	mkdir -p $(dirname ${out})
	pandoc --standalone --template=${TEMPLATE} --to=html5 ${in} > ${out}
}

dev() {
	trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
	httpwatcher --root ${DESTDIR} --port 8000 --no-browser &
	while sleep 0.1; do
		find ${SRCDIR} ${STATICDIR} ${TEMPLATE} | entr -dp ${0} --build
	done
}

if [[ ${1} == "-b" || ${1} == "--build" ]]; then
	build
elif [[ ${1} == "-d" || ${1} == "--dev" ]]; then
	build && dev
else
	echo "usage: ssg [-bd]"
fi