#!/bin/bash

SRCDIR="${PWD}/src"
DESTDIR="${PWD}/dest"
STATICDIR="${PWD}/static"
TEMPLATE="${PWD}/template.html"
BLOGDIR="${PWD}/src/blog/"
BLOGTITLE="Blog"

set -e
conf="${PWD}/ssg.conf"
if [ -f ${conf} ]; then
	. ${conf}
fi

build() {
	rm -rf ${DESTDIR}/
	mkdir ${DESTDIR}/
	for f in $(find ${SRCDIR}/ -type f,l); do
		path=${f#${SRCDIR}}
		base=${path%.*}
		out="${DESTDIR}${base}.html"
		mkdir -p $(dirname ${out})
		pandoc \
			-standalone \
			--template=${TEMPLATE} \
			--to=html \
			${f} > ${out}
	done
	cp -a ${STATICDIR}/. ${DESTDIR}/
	echo "build complete"
}

blog() {
	index="${BLOGDIR}/index.md"
	if [ -f ${index} ]; then
		rm ${index}
	fi
	touch ${index}
	echo "---" >> ${index}
	echo "title: ${BLOGTITLE}" >> ${index}
	echo "---" >> ${index}
	echo "" >> ${index}
	echo "# ${BLOGTITLE}" >> ${index}
	for f in ${BLOGDIR}/*.md; do
		if [ "${f}" == ${index} ]; then
			continue
		fi
		b=$(basename ${f})
		title=${b%.md}
		path=${f#${SRCDIR}}
		href="${path%.md}.html"
		echo "* [${title}](${href})" >> ${index}
	done
	echo "index blog"
}

dev() {
	set +e
	trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
	httpwatcher --root ${DESTDIR} --port 8000 --no-browser &
	while sleep 0.1; do
		if [ "${blog}" = true ]; then
			cmd="${0} -bl"
		else
			cmd="${0} -b"
		fi
		find ${SRCDIR} ${STATICDIR} ${TEMPLATE} | entr -dp ${cmd}
	done
}

pathErr() {
	if test -f "${conf}"; then
		echo "config error: ${conf}"
	fi
	echo "invalid path: ${1}"
	exit 1;
}

checkPaths() {
	if [ ! -d ${SRCDIR} ]; then
		pathErr ${SRCDIR}
	elif [ ! -d ${DESTDIR} ]; then
		pathErr ${DESTDIR}
	elif [ ! -d ${STATICDIR} ]; then
		pathErr ${STATICDIR}
	elif [ ! -d ${BLOGDIR} ]; then
		pathErr ${BLOGDIR}
	elif [ ! -f ${TEMPLATE} ]; then
		pathErr ${TEMPLATE}
	fi
}

usage() {
	echo "usage: ssg [-bld]"
	echo "help: man ssg"
	exit 1
}

if [ $# -eq 0 ]; then
	usage
fi
while getopts ":bld" arg; do
	case "${arg}" in
		b)
			build=true
			;;
		l)
			blog=true
			;;
		d)
			dev=true
			;;
		*)
			usage
			;;
	esac
done
if [ "${blog}" = true ]; then
	blog
fi
if [ "${build}" = true ]; then
	build
fi
if [ "${dev}" = true ]; then
	dev
fi