#!/bin/sh

SRCDIR=""
DESTDIR=""
STATICDIR=""
TEMPLATE=""

build() {
	rm -rf ${DESTDIR}/
	mkdir ${DESTDIR}/
	for f in $(find ${SRCDIR}/ -type f,l); do
		if [ "${f}" = ${TEMPLATE} ]; then
			continue
		fi
		path=${f#${SRCDIR}}
		base=${path%.*}
		out="${DESTDIR}${base}.html"
		mkdir -p $(dirname ${out})
		pandoc \
			-V date="$(date +'%B %d, %Y')" \
			-standalone \
			--template=${TEMPLATE} \
			--to=html \
			${f} > ${out}
	done
	cp -a ${STATICDIR}/. ${DESTDIR}/
	echo "build complete"
}

usageMsg() {
	echo "usage: ssg [-b]"
	echo "help: man ssg"
	exit 1
}

noConfig() {
	echo "no config: ${conf}"
	echo "help: man ssg"
	exit 1
}

configErr() {
	echo "config error: ${conf}"
	echo "${1}"
	echo "help: man ssg"
	exit 1;
}

checkConfig() {
	if [ -z ${SRCDIR} ]; then
		configErr "missing var: SRCDIR"
	elif [ -z ${DESTDIR} ]; then
		configErr "missing var: DESTDIR"
	elif [ -z ${STATICDIR} ]; then
		configErr "missing var: STATICDIR"
	elif [ -z ${TEMPLATE} ]; then
		configErr "missing var: TEMPLATE"
	elif [ ! -d ${SRCDIR} ]; then
		configErr "invalid path: ${SRCDIR}"
	elif [ ! -d ${DESTDIR} ]; then
		configErr "invalid path: ${DESTDIR}"
	elif [ ! -d ${STATICDIR} ]; then
		configErr "invalid path: ${STATICDIR}"
	elif [ ! -f ${TEMPLATE} ]; then
		configErr "invalid path: ${TEMPLATE}"
	fi
}

set -eu
conf="${PWD}/ssg.conf"
if [ -f ${conf} ]; then
	. ${conf}
	checkConfig
else
	noConfig
fi
if [ $# -eq 0 ]; then
	usageMsg
fi
if [ ${1} = "-b" ]; then
	build
else
	usageMsg
fi